# Generated by Django 3.0.3 on 2020-03-08 16:56

import School.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sutdentAdmissionNumber', models.IntegerField(max_length=10)),
                ('studentFirstName', models.CharField(max_length=100)),
                ('studentLastName', models.CharField(max_length=100)),
                ('studentFatherName', models.CharField(max_length=100)),
                ('studentMotherName', models.CharField(max_length=100)),
                ('studentAddress', models.CharField(max_length=400)),
                ('studentClass', models.IntegerField(max_length=2)),
                ('studentSection', models.CharField(max_length=2)),
                ('studentNumber', models.IntegerField(max_length=10)),
                ('studentSlug', models.SlugField()),
                ('studentPhoto', models.ImageField(upload_to=School.models.studentImageUploadPath)),
                ('studentDateOfBirth', models.DateField()),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
    ]
