# Generated by Django 3.0.3 on 2020-03-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0002_teachingstaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='studentEmail',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='teachingstaff',
            name='teacherEmail',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='teachingstaff',
            name='teacherNumber',
            field=models.IntegerField(max_length=11, null=True),
        ),
    ]
