# Generated by Django 3.0.3 on 2020-03-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0003_auto_20200308_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingstaff',
            name='teacherAddress',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
