# Generated by Django 3.0.3 on 2020-03-08 16:56

import SchoolAdmin.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NonTeachingStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntFirstName', models.CharField(max_length=100)),
                ('ntLastName', models.CharField(max_length=100)),
                ('ntFatherName', models.CharField(max_length=100)),
                ('ntPost', models.CharField(max_length=100)),
                ('ntImage', models.ImageField(upload_to=SchoolAdmin.models.NonTeachingStaffImageUpload)),
                ('ntDateOfBirth', models.DateField(null=True)),
                ('ntJoiningDate', models.DateField(default=datetime.datetime(2020, 3, 8, 22, 26, 8, 774277))),
                ('ntSlug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Non Teaching Staff',
                'verbose_name_plural': 'Non Teaching Staff',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noticeName', models.CharField(max_length=50)),
                ('noticeText', models.CharField(max_length=200)),
                ('noticeDate', models.DateField(default=datetime.datetime(2020, 3, 8, 22, 26, 8, 775308))),
                ('noticeAssocFile', models.FileField(null=True, upload_to='')),
                ('noticeSlug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Notice',
                'verbose_name_plural': 'Notices',
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteTitle', models.CharField(max_length=150)),
                ('siteLogo', models.ImageField(upload_to=SchoolAdmin.models.SiteLogoImagesUploadPath)),
                ('siteBannerImages', models.ImageField(upload_to=SchoolAdmin.models.SiteLogoImagesUploadPath)),
                ('sitePrincipalMessage', models.CharField(max_length=200)),
                ('siteDirectorMessage', models.CharField(max_length=200)),
                ('priPhoto', models.ImageField(upload_to=SchoolAdmin.models.SiteLogoImagesUploadPath)),
                ('DirPhoto', models.ImageField(upload_to=SchoolAdmin.models.SiteLogoImagesUploadPath)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='SchoolAdminUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userProfile', models.ImageField(upload_to=SchoolAdmin.models.UserImageUploadPath)),
                ('userSlug', models.SlugField()),
                ('userAdmin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin User',
                'verbose_name_plural': 'Admin User',
            },
        ),
    ]
