# Generated by Django 3.0.3 on 2020-03-08 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonteachingstaff',
            name='ntJoiningDate',
            field=models.DateField(default=datetime.datetime(2020, 3, 8, 22, 42, 0, 646423)),
        ),
        migrations.AlterField(
            model_name='notice',
            name='noticeDate',
            field=models.DateField(default=datetime.datetime(2020, 3, 8, 22, 42, 0, 647246)),
        ),
    ]
