# Generated by Django 3.0.3 on 2020-03-08 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolAdmin', '0002_auto_20200308_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonteachingstaff',
            name='ntEmail',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='nonteachingstaff',
            name='ntJoiningDate',
            field=models.DateField(default=datetime.datetime(2020, 3, 8, 22, 54, 28, 553524)),
        ),
        migrations.AlterField(
            model_name='notice',
            name='noticeDate',
            field=models.DateField(default=datetime.datetime(2020, 3, 8, 22, 54, 28, 554605)),
        ),
    ]
