# Generated by Django 3.0.3 on 2020-03-10 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolAdmin', '0003_auto_20200308_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='noticeIsPublished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='nonteachingstaff',
            name='ntJoiningDate',
            field=models.DateField(default=datetime.datetime(2020, 3, 11, 0, 2, 27, 312836)),
        ),
        migrations.AlterField(
            model_name='notice',
            name='noticeDate',
            field=models.DateField(default=datetime.datetime(2020, 3, 11, 0, 2, 27, 313688)),
        ),
    ]
