# Generated by Django 3.0.3 on 2020-03-12 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolAdmin', '0004_auto_20200311_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonteachingstaff',
            name='ntJoiningDate',
            field=models.DateField(default=datetime.datetime(2020, 3, 12, 23, 54, 59, 592601)),
        ),
        migrations.AlterField(
            model_name='notice',
            name='noticeDate',
            field=models.DateField(default=datetime.datetime(2020, 3, 12, 23, 54, 59, 593450)),
        ),
    ]
