# Generated by Django 3.0.3 on 2020-03-21 05:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolAdmin', '0005_auto_20200312_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonteachingstaff',
            name='ntAddress',
            field=models.TextField(default='null', max_length=300),
        ),
        migrations.AddField(
            model_name='nonteachingstaff',
            name='ntPhoneNu',
            field=models.IntegerField(default=0, max_length=11),
        ),
        migrations.AlterField(
            model_name='nonteachingstaff',
            name='ntJoiningDate',
            field=models.DateField(default=datetime.datetime(2020, 3, 21, 11, 20, 54, 784208)),
        ),
        migrations.AlterField(
            model_name='notice',
            name='noticeAssocFile',
            field=models.FileField(default='null', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='notice',
            name='noticeDate',
            field=models.DateField(default=datetime.datetime(2020, 3, 21, 11, 20, 54, 785148)),
        ),
    ]
